name:                aoc2019-haskell-solutions
version:             0.1.0.0
github:              "Belinsky-L-V/aoc2019-haskell-solutions"
license:             BSD3
author:              "Leonid Belinsky"
copyright:           "2019 Leonid Belinsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Belinsky-L-V/aoc2019-haskell-solutions#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12.0.3 && < 0.13
- containers >= 0.6.0.1 && < 0.7
- text >= 1.2.3.1 && < 1.3
- megaparsec >= 7.0.5 && < 7.1
- transformers >= 0.5.6.2 && < 0.6
- fgl >= 5.7.0.1 && < 5.8
- streaming >= 0.2.3.0 && < 0.3
- foldl >= 1.4.5 && < 1.5

library:
  source-dirs: src

executables:
  d1:
    main:                day1.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d2:
    main:                day2.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d3:
    main:                day3.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d4:
    main:                day4.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d5:
    main:                day5.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d6:
    main:                day6.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d7:
    main:                day7.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions

  d8:
    main:                day8.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019-haskell-solutions
